title = "Bartłomiej Warzecha IT/Life-Style blog"
baseURL = "https://lively-coast-0e4026f03.azurestaticapps.net"
theme = "bilberry-hugo-theme"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end./
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "enable"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "enable"

# Enable / Disable open link with a new tab.
[blackfriday]
  hrefTargetBlank = false

[params]
  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Bartłomiej Warzecha"
  description = "IT/Life-Style Bartłomiej Warzecha blog "
  keywords = "blog,C#, .NET, Problem Solving, personal, IT, Programming, Bartłomiej Warzecha, Warzecha, responsive,search,font awesome,pages,posts,multilingual,syntax ,shortcuts"

  # How many articles should be displayed at once?
  paginate = 5

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "V0BFXPJRHM"
  algolia_apiKey    = "5291b8a6b4bc97493dae7853e44b0466"
  algolia_indexName = "bawarzec"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = true

  # Enable / Disable comments on the articles via commento
  commentoJsURL = ""

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Hello World!"

    # if you want to use libravatar or gravatar for the header image
    avatarEmail = "bartlomiejwarzecha2@gmail.com"

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = ""

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    # pinnedPost = "/article/installing-bilberry-theme/"
    # Set to true to pin only to the first page, false to all pages
    # pinOnlyToFirstPage = false

    # enable automatic localization of the article's PublishedDate with momentjs
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = -1

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 20

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      # { link = "https://twitter.com/TheRealLednerb", icon = "fab fa-twitter" },
      { link = "https://github.com/BartlomiejWarzecha", icon = "fab fa-github" },
    ]

    # credits line configuration
    copyrightBy = "by BartlomiejWarzecha"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    # copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/BartlomiejWarzecha"
    creditsText = "Bartlomiej Warzecha blog"
    creditsUrl = "https://github.com/BartlomiejWarzecha"


# customize your available languages for your multi-lingual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.pl]
    weight = 2
    title = "Bartłomiej Warzecha IT/Life-Style blog"
    subtitle = "Witaj świecie!"

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
